apiVersion: v1 # Specifies the API version for Kubernetes resources
kind: Secret # Declares that this resource is a Secret
metadata:
  name: argocd-image-updater-git-creds # Name of the Secret object
  namespace: argocd # Namespace where the Secret will be created
stringData:
  username: "YOUR_GITHUB_USERNAME" # Your GitHub username for authentication
  password: "PAT_TOKEN_GITHUB" # Your GitHub personal access token for authentication
