apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yash252525/ArgoCD_Application_Deployments.git
    targetRevision: main
    path: ArgoCD_multiclusters/online-shop # Path within the repo
  destination:
    server: https://172.31.1.26:33893 # Production cluster API server URL here, run `argocd cluster list` to get the URL
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
